
-- CUSTOMER TABLE
CREATE TABLE IF NOT EXISTS CUSTOMER(
    CUSTOMER_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(100) NOT NULL, 
    CUSTOMER_EMAIL VARCHAR(100) NOT NULL,
    CUSTOMER_PASSWORD VARCHAR(20) NOT NULL,
    CUSTOMER_ADDRESS VARCHAR(100) DEFAULT NULL,
    CUSTOMER_TEL_NUM INT(10) DEFAULT NULL
);

-- PRODUCT TABLE
CREATE TABLE IF NOT EXISTS ARTWORKS(
    ARTWORK_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ARTWORK_NAME VARCHAR(100) NOT NULL, 
    ARTWORK_DIMENSIONS VARCHAR(100) NOT NULL, 
    ARTWORK_DESC VARCHAR(1000) NOT NULL, 
    ARTWORK_PRICE DECIMAL(10, 2) NOT NULL, 
    ARTIST_NAME VARCHAR(30) NOT NULL,
    CATEGORY_ID INT(11),

);

-- CART TABLE
CREATE TABLE IF NOT EXISTS CART(
    CART_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INT(11) NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) 
);

-- ORDER TABLE
CREATE TABLE IF NOT EXISTS ORDERS(
    ORDERS_ID INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ORDERS_AMOUNT DECIMAL(5,2) NOT NULL,
    CUSTOMER_ID INT(11) NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) 
);

CREATE TABLE IF NOT EXISTS PAYMENT(
    PAYMENT_ID INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PAYMENT_METHOD VARCHAR(50) NOT NULL,
    CUSTOMER_ID INT(11) NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) 
);


CREATE TABLE IF NOT EXISTS CATEGORY(
    CATEGORY_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CATEGORY_NAME VARCHAR(50) NOT NULL,
    CATEGORY_DESC VARCHAR(50) NOT NULL
);


