-- Checking the right database is used
USE artify;
SELECT DATABASE();


-- CUSTOMER TABLE
CREATE TABLE IF NOT EXISTS CUSTOMER(
    CUSTOMER_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(100) NOT NULL, 
    CUSTOMER_EMAIL VARCHAR(100) NOT NULL,
    CUSTOMER_PASSWORD VARCHAR(20) NOT NULL,
    CUSTOMER_ADDRESS VARCHAR(100) NOT NULL,
    CUSTOMER_TEL_NUM INT(10) NOT NULL
);


-- ARTWORKS TABLE
CREATE TABLE IF NOT EXISTS ARTWORKS(
    ARTWORK_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ARTWORK_NAME VARCHAR(100) NOT NULL, 
    ARTWORK_DIMENSIONS VARCHAR(100) NOT NULL, 
    ARTWORK_DESC VARCHAR(5000) DEFAULT NULL, 
    ARTWORK_PRICE DECIMAL(10, 2) NOT NULL, 
    ARTIST_NAME VARCHAR(30) NOT NULL,
    ARTWORK_URL VARCHAR(255) NOT NULL,
    STOCK INT(8) NOT NULL,
    CATEGORY_ID INT,
    CONSTRAINT FK_ArtCategory FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID) ON DELETE CASCADE
);


-- CART TABLE
CREATE TABLE IF NOT EXISTS CART(
    CART_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INT,
    CONSTRAINT FK_CustomerCart FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE
);


-- CART ITEM TABLE
CREATE TABLE IF NOT EXISTS CART_ITEM(
    CART_ITEM_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    QUANTITY INT,
    CART_ID INT,
    CONSTRAINT Fk_Cus_Cart_Info FOREIGN KEY (CART_ID) REFERENCES CART(CART_ID) ON DELETE CASCADE,
    ARTWORK_ID INT,
    CONSTRAINT FK_CartArtwork FOREIGN KEY (ARTWORK_ID) REFERENCES ARTWORKS(ARTWORK_ID) ON DELETE CASCADE
);



-- ORDERS TABLE
CREATE TABLE IF NOT EXISTS ORDERS(
    ORDERS_ID INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ORDER_DATE DATETIME NOT NULL, 
    TOTAL_AMOUNT DECIMAL(10,2) NOT NULL,
    SHIPPING_STATUS ENUM("Pending", "Successfully Shipped"),
    CUSTOMER_ID INT,
    CONSTRAINT Fk_CustomerOrder FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE
);


-- ORDER_DETAILS TABLE
CREATE TABLE IF NOT EXISTS ORDERS_DETAILS(
    ORDER_DETAILS_ID INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    QUANTITY INT(100) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    ORDERS_ID INT, 
    CONSTRAINT Fk_OrderDetails_Cus FOREIGN KEY (ORDERS_ID) REFERENCES ORDERS(ORDERS_ID) ON DELETE CASCADE
);

-- PAYMENT TABLE
CREATE TABLE IF NOT EXISTS PAYMENT(
    PAYMENT_ID INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PAYMENT_METHOD VARCHAR(50) NOT NULL,
    CUSTOMER_ID INT,
    CONSTRAINT FK_CustomerPay FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE
);


-- ADMIN TABLE 
CREATE TABLE IF NOT EXISTS ADMINS(
    ADMIN_ID INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ADMIN_NAME VARCHAR(255) NOT NULL,
    ADMIN_PASSWORD VARCHAR(20) NOT NULL
);


-- CATEGORY TABLE (ADMIN)
CREATE TABLE IF NOT EXISTS CATEGORY(
    CATEGORY_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CATEGORY_NAME VARCHAR(100) NOT NULL,
    CATEGORY_DESC VARCHAR(5000) NOT NULL
);


-- Sample records for Customer
DELETE FROM CUSTOMER;
INSERT INTO CUSTOMER VALUES(1101, "Lisa", "lisajones@email.com", "password101", "Bikini Bottom street", "0123456789");
INSERT INTO CUSTOMER VALUES(1102, "Nathan", "nathannnn@email.com", "101drowssap", "Mushroom Land", "0112456789");


-- Sample records for Artworks 
DELETE FROM ARTWORKS;
INSERT INTO ARTWORKS VALUES(1, "Lisa Mona", "20 x 30 (inches)", "A painting of a beautiful woman from the 90s", 250, "Leonardo Da Vinci", "src/images/painting_1.jpg", 1000, 100);
INSERT INTO ARTWORKS VALUES(2, "A girl with a fabulous earring", "20 x 30 (inches)", "A painting of a beautiful woman and her fabulous earring from the 90s", 250, "Johannes Vermeer", "src/images/painting_2.jpg", 1000, 100);
INSERT INTO ARTWORKS VALUES(3, "Jett: Collector's edition", "40 x 20 (inches)", "Jett is now available in all her glory!", 120, "VALORANT", "src/images/poster_1.jpg", 500, 102);
INSERT INTO ARTWORKS VALUES(4, "Haven: Collector's edition", "50 x 30 (inches)", "Decorate your room with one of VALORANT's unique maps", 160, "VALORANT", "src/images/poster_2.jpg", 500, 102);
INSERT INTO ARTWORKS VALUES(5, "Elegant Hunter Of The Night", "30 x 30 (inches)", "Swifting through the breeze, in depths of the darkness, lurks elegance that travels high", 160, "mich-spich", "src/images/pixel_1.png", 500, 101);
INSERT INTO ARTWORKS VALUES(6, "Packaging Across The Solar System", "20 x 20 (inches)", "Move along the orbit!", 160, "Kellay9", "src/images/pixel_2.png", 500, 101);


-- Sample records for Cart
DELETE FROM CART;
INSERT INTO CART VALUES(201, 1101);
INSERT INTO CART VALUES(202, 1102);


-- Sample records for Cart Item
DELETE FROM CART_ITEM;
INSERT INTO CART_ITEM VALUES(301, 2, 2, 201);
INSERT INTO CART_ITEM VALUES(302, 3, 3, 201);
INSERT INTO CART_ITEM VALUES(303, 1, 1, 202);


-- Sample records for Cateogry
DELETE FROM CATEGORY;
INSERT INTO CATEGORY VALUES(100, "Painting" ,"Gems made with love");
INSERT INTO CATEGORY VALUES(101, "Digital"  ,"Tiny squares put together to forge a masterpiece");
INSERT INTO CATEGORY VALUES(102, "Poster" ,"A curated collection of aesthetics");


 


