
-- CUSTOMER TABLE
CREATE TABLE IF NOT EXISTS CUSTOMER(
    CUSTOMER_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(100) NOT NULL, 
    CUSTOMER_EMAIL VARCHAR(100) NOT NULL,
    CUSTOMER_PASSWORD VARCHAR(20) NOT NULL,
    CUSTOMER_ADDRESS VARCHAR(100) DEFAULT NULL,
    CUSTOMER_TEL_NUM INT(10) DEFAULT NULL
);


-- PRODUCT TABLE
CREATE TABLE IF NOT EXISTS PRODUCT(
    PRODUCT_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_NAME VARCHAR(100) NOT NULL, 
    PRODUCT_DESC VARCHAR(1000) NOT NULL, 
    PRODUCT_PRICE DECIMAL(10, 2) NOT NULL, 
    PRODUCT_ARTIST VARCHAR(30) NOT NULL
);

-- CART TABLE
CREATE TABLE IF NOT EXISTS CART(
    CART_ID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INT(11),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) 
);

-- ORDER TABLE
CREATE TABLE IF NOT EXISTS ORDERS(
    ORDER_ID INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ORDER_AMOUNT DECIMAL(5,2) NOT NULL
);


